package com.tecstorm.housematch.entities;

public enum PersonalityLevel {
    EARLY_BIRD, NIGHT_OWL,
    INTROVERT, AMBIVERT, EXTROVERT,
    RELAXED, STRICT,
    CASUAL, INTENSIVE,
    HOMEBODY, ADVENTUROUS,
    FITNESS_FOCUSED, HUSTLE_MODE, PARTY_DRIVEN, ERASMUS_MODE,
    BALANCED, MODERATE, FLEXIBLE
}
